version: "3.9"

services:
  mariadb:
    build: ./mariadb
    container_name: mariadb
    environment:
      - "MARIADB_DATABASE=filefort"
    env_file:
      - mariadb/.env

  flask:
    build: ./flask
    ports:
      - "8080:8080"
    container_name: flask
    env_file:
      - mariadb/.env
      - flask/.env
    volumes:
      - file_storage:/mnt/file_storage

  nginx:
    build: ./nginx/
    volumes:
      - file_storage:/srv/file_storage


volumes:
  file_storage:
    name: "file_storage"
