name: Flask Server

on:
  pull_request:
    types: [opened, ready_for_review]
  push:
    branches:
      '**' # all branches
  
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        working-directory: ./flask/
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        working-directory: ./flask/
        run: python -m pip install -r requirements.txt pytest pytest-mock
      - name: Test with pytest
        working-directory: ./flask/
        run: pytest
