name: MariaDB

on:
  pull_request:
    types: [opened, ready_for_review]
  push:
    branches:
      '**' # all branches

jobs:
  run_tests:
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:latest
        env:
          MARIADB_ROOT_PASSWORD: password
          MARIADB_DATABASE: filefort
          MARIADB_USER: test_user
          MARIADB_PASSWORD: password
        ports:
          - 3306:3306
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install mariadb client
        run: |
          sudo apt update
          sudo apt install mariadb-client -y
      - name: Install testing dependencies
        working-directory: ./mariadb/
        run: python -m pip install -r ./tests/requirements.txt
      - name: Initialize database
        working-directory: ./mariadb/
        run: |
          mariadb --protocol=tcp -u root -ppassword filefort < ./init.sql
          mariadb --protocol=tcp -u root -ppassword filefort < ./procedures.sql
      - name: Test with pytest
        working-directory: ./mariadb/
        env:
          MARIADB_USER: test_user
          MARIADB_PASSWORD: password
        run: pytest
